export const ADD_COMMENT = 'ADD_COMMENT';
export const DISH_LOADING='DISH_LOADING' ;
export const ADD_DISH ='ADD_DISH';
export const DISH_FAILED='DISH_FAILED';
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED"; 
export const ADD_PROMOS = "ADD_PROMOS"; 
export const PROMOS_LOADING = "PROMOS_LOADING";
export const PROMOS_FAILED = "PROMOS_FAILED"; 